# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=100000.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='StockQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ask_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='portfolioentry',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Stock'),
        ),
    ]
