# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20170204_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockquery',
            name='stock',
        ),
        migrations.DeleteModel(
            name='StockQuery',
        ),
    ]
