# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_orderhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
